;;; alg-gptel-helpers-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from alg-gptel-export.el

(autoload 'alg/gptel-export-to-markdown-buffer "alg-gptel-export" "\
Export the current gptel buffer to a new markdown buffer.
Creates a new buffer with the exported markdown content and displays it." t)
(register-definition-prefixes "alg-gptel-export" '("alg-gptel-export--"))


;;; Generated autoloads from alg-gptel-helpers.el

(autoload 'alg/org-kill-file-link "alg-gptel-helpers" "\
Places a org link to the current file on the yank buffer" t)


;;; Generated autoloads from alg-gptel-highlighter.el

(autoload 'alg/gptel-toggle-highlight "alg-gptel-highlighter" "\
Toggle diagnostic highlighting of gptel response regions in an Org buffer using overlays.

Reads response extents from the buffer's :GPTEL_BOUNDS: property." t)
(autoload 'alg/gptel-toggle-verbosity "alg-gptel-highlighter" "\
Toggle Gptel's logging verbosity." t)
(register-definition-prefixes "alg-gptel-highlighter" '("gptel-org--"))


;;; Generated autoloads from alg-gptel-prompts.el

(register-definition-prefixes "alg-gptel-prompts" '("alg"))


;;; Generated autoloads from alg-gptel-savechat.el

(autoload 'alg/gptel-save-chat "alg-gptel-savechat" "\
Prompt for a filename and save the current buffer to it.
The prompt is prefilled with '~/Documents/chats/YYYY-MM-DD-chat-'
where YYYY-MM-DD is the current date. The user can then
complete the filename.

(fn FILENAME)" t)


;;; Generated autoloads from alg-gptel-saverestore.el

(autoload 'alg/gptel-context-save "alg-gptel-saverestore" "\
Save current gptel context as elisp code in the current buffer.
Inserts code that when evaluated will restore the current context,
including files (with absolute paths), buffer names, and selected tools." t)
(autoload 'alg/gptel-context-restore "alg-gptel-saverestore" "\
Initialize gptel context with specified FILES, BUFFERS and TOOLS.

FILES is a list of file paths (tildes will be expanded).
BUFFERS is a list of buffer names as strings.
TOOLS is a list of tool names as strings.

Clears existing context and tools before initializing new ones.

(fn FILES BUFFERS TOOLS)")
(autoload 'alg/gptel-context-clear "alg-gptel-saverestore" "\
Clears context and tools" t)


;;; Generated autoloads from alg-gptel-upgrade.el

(autoload 'alg/gptel-upgrade "alg-gptel-upgrade" "\
Offer to upgrade gptel to latest version and remove older versions." t)

;;; End of scraped data

(provide 'alg-gptel-helpers-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; alg-gptel-helpers-autoloads.el ends here
